# Generated by Django 3.1.7 on 2021-03-13 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ifsc',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bank_name', models.CharField(max_length=50)),
                ('ifsc', models.CharField(max_length=30)),
                ('micr_code', models.IntegerField()),
                ('branch', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=100)),
                ('std_code', models.IntegerField()),
                ('city', models.CharField(max_length=50)),
                ('district', models.CharField(max_length=30)),
                ('state', models.CharField(max_length=40)),
            ],
        ),
    ]
