# Generated by Django 3.1.7 on 2021-03-13 12:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0002_auto_20210313_1504'),
    ]

    operations = [
        migrations.CreateModel(
            name='IfscSearchTrack',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('search_time', models.DateTimeField(auto_now=True)),
                ('ifsc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bank.ifsc')),
            ],
        ),
    ]
