# Generated by Django 3.1.7 on 2021-03-13 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0003_ifscsearchtrack'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ifsc',
            name='micr_code',
            field=models.CharField(max_length=50),
        ),
    ]
